### ISSUE TITLE
update wishlist

### ISSUE THREAD

**Issue by kra** [kra/futel.net#16]
OpenWRT compatible routers (also update link)
Unlocked SIP ATA devices.
Payphones and payphone enclosures.
Desk/home phones.
IP phones. Here are some.
Digium cards, any revision will do. Here’s an example.
Bulk RJ-11 cable or any standard phone cable. Builk power cable.
Concrete, conduit, and related installation hardware.

Digium reuires someone to use it, I don't have time for it right now and the person who was interested in developing that hasn't either for a while, but it would be very useful and economical to be able to do demos and shows with a pc, so probably keep that line.

Ditto for android phones with sip clients.

**Comment by lboom** [comment]
Updated wish list and links.
