### ISSUE TITLE
enable https

### ISSUE THREAD

**Issue by kra** [kra/futel.net#17]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by Jonty** [comment]
As a heads up, this is breaking your website for anyone who has the HTTPS Everywhere extension enabled. It's a fairly quick fix - [you just need to update the A records](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site) on your domain to point at:

> 185.199.108.153
> 185.199.109.153
> 185.199.110.153
> 185.199.111.153

And toggle the "Enforce HTTPS" box in the repo admin section after the DNS has propagated.

**Comment by kra** [comment]
https working without warnings for everything except https://www.futel.net

**Comment by kra** [comment]
https is now working for futel.net and www.futel.net?
what is left? We aren't redirecting http to https. Probably the "enforce https" setting mentioned above will do that?
