### ISSUE TITLE
make new blog

### ISSUE THREAD

**Issue by kra** [kra/futel.net#59]
copy content from current tumblr blog
make it not part of futel.net, own repo etc.

there is surely a github pages static blog generator

tumblr is getting hostile and the tumblr impl is making old posts hard to find

**Comment by breedx2** [comment]
FYI https://help.tumblr.com/hc/en-us/articles/360005118894-Export-Your-Blog
Obv that's not a completely solution, but it's a way to quickly/easily get the content out. No clue what it looks like in there though.

**Comment by breedx2** [comment]
Also https://github.com/jaanus/tumblr2markdown seems pretty straightforward. 

The [dorkbot site](https://github.com/dorkbotpdx/dorkbotpdx.org) is a plain jekyll site that publishes automatically these days. Can be used as a reference.

If you wanna scrape the data and throw it up in a blogs repo under the futel org, I can help set up the pages stuff.
