### ISSUE TITLE
footer issues for georgemandis:gh-pages branch

### ISSUE THREAD

**Issue by kra** [kra/futel.net#7]
Footer has a link to /locations, dead link. Issue #4 could probably be a destination for that someday.

The footer is kind of redundant to lots of pages, maybe we can think of some alternatives. Kind of bogus on the /about page, maybe just remove it from the body there. But it's probably good to have it in the /wishlist body, and I like it in the middle of the /support body. Maybe move it from a footer to the bottom of the left nav? But the left nav is on top for the mobile version, so that might not work so well. Maybe just remove it from /about body and figure this out later.

**Comment by georgemandis** [comment]
I fixed the dead link and just removed the contact info from the "about" page for now. Should be in latest pull-request: 

https://github.com/kra/futel.net/pull/5
