### ISSUE TITLE
sidebar images should be the same size and not cutoff

### ISSUE THREAD

**Issue by x37v** [kra/futel.net#9]
The sidebar that shows the menu has an image above and below the link text.. the black basic futel logo and a variety of others below.. it would be really nice if these were the same size as the alignment is a bit awkward at this point.  The lightning image is also partially cut off..

I looked into fixing it up myself but don't quite get how to customize the bootstrap stuff.
![screen shot 2016-11-28 at 2 26 24 pm](https://cloud.githubusercontent.com/assets/65796/20688677/b2e479c6-b576-11e6-95ac-b7320f3f7e02.png)

**Comment by georgemandis** [comment]
There was a "max-height" set for the logo to make it less gigantic on mobile. It was mistakenly being implemented on desktop as well, but I fixed it just now. Any image that appears on that column should max-out at 100% of the column-width and auto-adjust the height.

I'm not exactly seeing the cut-off on the lightning image... You can look at the full image here:

[http://futel.net/images/futel.net-lightning.png](http://futel.net/images/futel.net-lightning.png)

What I *am* noticing though is there's a little white space in the image on the left and right side. That could be trimmed so it looks more like the logo at the top.

**Comment by x37v** [comment]
looks much better.. I think the cut-off that I thought I saw was an artifact of my debugger.

Awesome!
